export const rooms = [
  {
    slug: "premium-deluxe-cabana",
    name: "Premium Deluxe Sea View Cabana",
    size: "33m²",
    capacity: "Up to 2 guests",
    amenities: [
      "California King-Size Bed (organic memory foam)",
      "Large terrace with loungers & desk",
    ],
    description:
      "Our signature sea view cabana pairs contemporary comfort with locally crafted finishes. Wake to the sounds of the bay, enjoy sunrise coffee on your terrace, and let our concierge tailor each day of your stay.",
    heroImage: "/images/rooms/premium-deluxe-sea-view-cabana-front-entrance-sea-view.avif",
    images: [
      "/images/rooms/premium-deluxe-sea-view-cabana-front-entrance-sea-view.avif",
      "/images/rooms/premium-deluxe-sea-view-cabana-angle-exterior-terrace-dolphin-bay.avif",
      "/images/rooms/premium-deluxe-sea-view-cabana-angled-view-terrace-ocean.avif",
      "/images/rooms/premium-deluxe-sea-view-cabana-bathroom-modern-design.avif",
      "/images/rooms/premium-deluxe-sea-view-cabana-shower-bathroom-luxury.avif",
    ],
  },
  {
    slug: "sea-view-cabana",
    name: "Sea View Cabana",
    size: "20m²",
    capacity: "Up to 2 guests",
    amenities: [
      "King-size bed",
      "Renovated February 2024",
    ],
    description:
      "Cozy cabanas designed for effortless indoor-outdoor living. Perfect for couples seeking easy access to our swim platform and curated island adventures.",
    heroImage: "/images/rooms/sea-view-cabana-front-entrance-ocean-view.avif",
    images: [
      "/images/rooms/sea-view-cabana-front-entrance-ocean-view.avif",
      "/images/rooms/sea-view-cabana-side-exterior-view.avif",
      "/images/rooms/sea-view-cabana-door-interior-view.avif",
      "/images/rooms/sea-view-cabana-bathroom-modern-design.avif",
    ],
  },
  {
    slug: "dolphin-view-room",
    name: "Dolphin View Room",
    size: "30m²",
    capacity: "Up to 2 guests",
    amenities: [
      "King-size bed",
      "Large terrace with Dolphin Bay view",
      "Desk & chair",
    ],
    description:
      "Watch pods of dolphins travel the bay from the privacy of your terrace. Ideal for guests blending work and wanderlust.",
    heroImage: "/images/rooms/dolphin-view-room-front-entrance-sea-view.avif",
    images: [
      "/images/rooms/dolphin-view-room-front-entrance-sea-view.avif",
      "/images/rooms/dolphin-view-room-front-side-exterior.avif",
      "/images/rooms/dolphin-view-room-bed-king-size-ocean-view.avif",
      "/images/rooms/dolphin-view-room-sea-view-from-bed.avif",
      "/images/rooms/dolphin-view-room-desk-chair-work-space.avif",
      "/images/rooms/dolphin-view-room-private-terrace-dolphin-bay.avif",
      "/images/rooms/dolphin-view-room-sea-view-from-terrace.avif",
      "/images/rooms/dolphin-view-room-private-bathroom.avif",
    ],
  },
  {
    slug: "family-jungle-room",
    name: "Family Jungle Room",
    size: "60m²+",
    capacity: "Sleeps up to 3 guests",
    amenities: [
      "1 King-size bed + 1 Twin day bed/sofa",
      "Bathtub & shower",
      "Terrace with sea & jungle views",
    ],
    description:
      "Spacious family sanctuary bordered by rainforest canopy. Perfect for longer stays, wellness retreats, and multi-generational escapes.",
    heroImage: "/images/rooms/family-jungle-room-front-entrance.avif",
    images: [
      "/images/rooms/family-jungle-room-front-entrance.avif",
      "/images/rooms/family-jungle-room-main-bed-king-size.avif",
      "/images/rooms/family-jungle-room-single-bed-twin.avif",
      "/images/rooms/family-jungle-room-both-beds-spacious.avif",
      "/images/rooms/family-jungle-room-single-bed-bathroom-view.avif",
      "/images/rooms/family-jungle-room-bathroom-modern.avif",
      "/images/rooms/family-jungle-room-bathtub-luxury.avif",
      "/images/rooms/family-jungle-room-sea-view-terrace.avif",
      "/images/rooms/family-jungle-room-hammock-terrace.avif",
      "/images/rooms/family-jungle-room-outdoor-seating-terrace.avif",
    ],
  },
];

export const diningHighlights = {
  heroImage: "/images/dining-overwater.jpg",
  description:
    "Blo Bar & Restaurant sits above the turquoise waters of Dolphin Bay, pairing European-inspired tasting menus with seasonal produce harvested steps away in our tropical gardens.",
  schedule: [
    { label: "Breakfast", detail: "8:00 – 9:30 am" },
    { label: "Lunch", detail: "12:00 – 2:30 pm" },
    { label: "Dinner", detail: "7:00 – 9:30 pm • three-course set menu" },
    { label: "Blo Bar", detail: "All-day snacks, fresh juices, and handcrafted cocktails" },
  ],
  testimonial:
    "Markus crafts cocktails from local botanicals while Yu hand-churns sorbets from garden fruit. Dinner feels like an invitation into the heart of Bocas.",
};

export const activities = [
  {
    slug: "snorkeling",
    name: "Snorkeling",
    summary: "Enjoy the Caribbean water directly from our swim platform or on an excursion with us! Snorkeling from our swim platform is free and included in your stay. Dive into the crystal-clear Caribbean waters from our swim platform or join guided snorkeling excursions to nearby coral reefs. Discover vibrant marine life in one of Panama's most biodiverse underwater ecosystems.",
    duration: "2-3 hours",
    difficulty: "Easy to Moderate",
    suitability: "Swimmers, ages 6+",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Free when snorkeling from our swim platform (included in your stay)",
      "Guided snorkeling excursions to coral reefs are paid activities - see individual tour listings for pricing",
    ],
    highlights: [
      "Free snorkeling from swim platform (included in your stay)",
      "Guided snorkeling at coral reefs (paid excursions)",
      "Swim platform access",
    ],
    included: [
      "Snorkeling equipment (mask, snorkel, fins) - free at swim platform",
      "Life vests",
      "Bilingual guide (for paid excursions)",
      "Boat transportation (for reef tours - paid excursions)",
    ],
    wildlife: [
      "Tropical reef fish",
      "Coral formations",
      "Sea stars and urchins",
      "Occasional rays",
      "Colorful parrotfish",
      "Angelfish and butterflyfish",
    ],
    whatToBring: [
      "Swimsuit",
      "Reef-safe sunscreen",
      "Underwater camera (optional)",
      "Towel",
      "Change of clothes",
    ],
    seasonal: false,
  },
  {
    slug: "water-ski-wakeboard",
    name: "Water Skiing/Wakeboarding",
    summary: "Explore wonderful places with our water sports adventure. Thrill yourself by Water Skiing or Wake Boarding. Experience the excitement of gliding over the crystal-clear waters of Dolphin Bay. Perfect for adrenaline seekers looking for an exhilarating water sports adventure. All tours include free snorkel equipment.",
    duration: "Up to 1 hour",
    difficulty: "Moderate to Advanced",
    suitability: "Ages 12+, swimmers",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$45 per person",
      "Up to 1 hour duration",
      "Includes instruction time on land and time in the water or on boat",
      "Price is per person and cannot be split between other people",
    ],
    highlights: [
      "Water skiing",
      "Wake boarding",
      "Free snorkel equipment included",
      "Instruction time on land included",
      "Time in the water or on boat",
    ],
    included: [
      "Equipment (skis, wakeboard)",
      "Boat and driver",
      "Safety equipment",
      "Basic instruction",
      "Snorkel equipment",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Change of clothes",
    ],
    seasonal: false,
  },
  {
    slug: "almirante-chocolate-farm-tour",
    name: "Almirante Mainland Chocolate Farm Tour",
    summary: "Tours include free tasting. Travel to Almirante on the mainland and visit an organic chocolate farm that belongs to the Ngabe tribe. Learn about the ways of life of the indigenous people and how they produce chocolate for big chocolate companies such as Lindt. The tour commences with a traditional Ngabe lunch of roots, rice, and chicken.",
    duration: "Full day",
    difficulty: "Easy",
    suitability: "Food lovers, all ages",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$225 for up to 2 people",
      "Includes boat ride to Almirante",
    ],
    highlights: [
      "Visit indigenous Ngabe cacao community",
      "Traditional Ngabe lunch (roots, rice, and chicken)",
      "Free chocolate tasting included",
      "Boat ride to Almirante included",
    ],
    included: [
      "Boat ride to Almirante",
      "Bilingual guide",
      "Chocolate tasting session",
      "Traditional Ngabe lunch",
    ],
    bookingNote: "Tour must be booked 24-48 hours ahead of time. We leave at 8:15 am or 12:15 pm. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [],
    whatToBring: [
      "Comfortable walking shoes",
      "Hat and sunscreen",
      "Camera",
      "Cash for purchasing chocolate products",
    ],
    seasonal: false,
  },
  {
    slug: "dolphin-bay-chocolate-tour",
    name: "Dolphin Bay Chocolate Tour",
    summary: "Tours include free tasting. Take our Kayak to our neighbor's award-winning chocolate farm. Learn how they produce Belgian-style chocolate. Have extra time? Stay for a chocolate workshop and learn how to make Belgian-style chocolate.",
    duration: "2 hours (workshop additional)",
    difficulty: "Easy",
    suitability: "Food lovers, all ages",
    image: "https://images.unsplash.com/photo-1511381939415-e44015466834?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Chocolate Tour:",
      "    $20 per person for 2 hours",
      "Chocolate Tour & Workshop:",
      "    $40 (paid directly at the farm)",
    ],
    highlights: [
      "Award-winning Belgian-style chocolate farm",
      "Free chocolate tasting included",
      "Kayak trip to neighbor's farm",
      "Optional chocolate workshop",
    ],
    included: [
      "Kayak transportation",
      "Chocolate tasting session",
      "Farm tour",
    ],
    bookingNote: "Chocolate tour & workshop is $40 paid directly at the farm. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [],
    whatToBring: [
      "Comfortable walking shoes",
      "Hat and sunscreen",
      "Camera",
      "Cash for chocolate workshop ($40, paid at farm)",
      "Cash for purchasing chocolate products",
    ],
    seasonal: false,
  },
  {
    slug: "stand-up-paddle",
    name: "Stand Up Paddle",
    summary: "Paddle as much as you like and for free at Dolphin Blue Paradise! Explore Dolphin Bay at your own pace with our stand-up paddleboards. Paddle through calm waters, observe marine life, and enjoy the tranquility of the bay from a unique perspective.",
    duration: "Flexible (1-4 hours)",
    difficulty: "Easy to Moderate",
    suitability: "All skill levels, ages 8+",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Free - included in your stay",
      "Paddle as much as you like",
    ],
    highlights: [
      "Free paddleboard access",
      "Dolphin Bay views",
      "Mangrove exploration",
    ],
    included: [
      "SUP board",
      "Paddle",
      "Life vest",
      "Basic instruction",
    ],
    wildlife: [
      "Dolphins (from a distance)",
      "Mangrove birds",
      "Fish in shallow waters",
      "Marine life in clear waters",
    ],
    whatToBring: [
      "Swimsuit or quick-dry clothing",
      "Sunscreen",
      "Hat and sunglasses",
      "Water bottle",
      "Waterproof bag for belongings",
    ],
    seasonal: false,
  },
  {
    slug: "surfing",
    name: "Surfing (Multiple Surf Schools Available)",
    summary: "From November - April. Catch a gnarly wave with one of our partner surf schools: Mono Loco Surf School, Bocas Surf School, or La Buga Dive & Surf. Various magazines rank Bocas Del Toro in the top Beach Breaks in the world. Catch a gnarly wave and if you're lucky you might just get barreled! Note: $90 boat transfer for 2 people not included in price.",
    duration: "Half-day to full-day",
    difficulty: "Moderate to Advanced",
    suitability: "Surfers, ages 12+",
    image: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Mono Loco Surf School:",
      "    Group lessons: $60 per person for 5 hours (includes board rental and rash guard)",
      "    Private lessons: $80 per person for 3 hours (includes board rental and rash guard)",
      "    Discounts for additional surfers",
      "Bocas Surf School:",
      "    $50 per person for 2 hours (30 min on land, 1.5 hours on waves)",
      "    3 Day surf camp: $140 per person",
      "La Buga Dive & Surf:",
      "    Half day lessons: $50",
      "    Full day lessons: $90",
      "    Surfboard rental: $20 (additional)",
      "Boat transfer: $90 for 2 people (not included in surf lesson price)",
    ],
    highlights: [
      "World-class surf breaks",
      "Multiple surf schools to choose from",
      "Surf camps available",
      "Board rental and rash guard included",
      "Group and private lessons available",
    ],
    included: [
      "Surfboard rental (varies by school)",
      "Transportation to surf spots",
      "Professional guide/instructor",
      "Safety equipment",
      "Rash guard (varies by school)",
    ],
    bookingNote: "$90 boat transfer for 2 people not included in price. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Marine life in surf zones",
      "Coastal birds",
    ],
    whatToBring: [
      "Swimsuit or wetsuit",
      "Reef-safe sunscreen",
      "Rash guard",
      "Towel",
      "Water bottle",
    ],
    seasonal: true,
    seasonNote: "Best conditions: November to April",
  },
  {
    slug: "kayak",
    name: "Kayak",
    summary: "A fun and free way to explore the bay by yourself and enjoy the view. Explore Dolphin Bay at your own pace with our kayaks. Paddle through calm waters, observe marine life, and enjoy the tranquility of the bay from a unique perspective.",
    duration: "Flexible (1-4 hours)",
    difficulty: "Easy",
    suitability: "All skill levels, ages 8+",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Free - included in your stay",
      "Kayak as much as you like",
    ],
    highlights: [
      "Free kayak access",
      "Dolphin Bay views",
      "Mangrove exploration",
    ],
    included: [
      "Kayak",
      "Paddle",
      "Life vest",
      "Basic instruction",
    ],
    wildlife: [
      "Dolphins (from a distance)",
      "Mangrove birds",
      "Fish in shallow waters",
      "Marine life in clear waters",
    ],
    whatToBring: [
      "Swimsuit or quick-dry clothing",
      "Sunscreen",
      "Hat and sunglasses",
      "Water bottle",
      "Waterproof bag for belongings",
    ],
    seasonal: false,
  },
  {
    slug: "monkey-island",
    name: "Monkey Island",
    summary: "Explore wonderful places with our private boat tour. Visit the monkey rescue center and interact with the monkeys. Besides experiencing the local monkeys on our very own property you can experience various species of monkeys on their own private island! Monkey Island is a sanctuary for orphaned monkeys belonging to a troop that socializes, grooms, and plays together every day. All tours include free snorkel equipment.",
    duration: "Half-day (3-4 hours)",
    difficulty: "Easy",
    suitability: "All ages, families welcome",
    image: "https://images.unsplash.com/photo-1540573133985-87b6da6d54a9?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Monkey Rescue Center:",
      "    $20 per person (paid directly to monkey rescue center)",
      "Boat Ride:",
      "    $100 for 2 people (includes soft drinks and water on board)",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Close encounters with rescued monkeys",
      "Photography opportunities",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Soft drinks and water on board",
      "Snorkel equipment",
      "Educational presentation",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "White-faced capuchin monkeys",
      "Howler monkeys",
      "Spider monkeys",
      "Squirrel monkeys",
    ],
    whatToBring: [
      "Comfortable clothing",
      "Closed-toe shoes",
      "Camera",
      "Insect repellent",
      "Cash for sanctuary entrance ($20 per person)",
    ],
    seasonal: false,
  },
  {
    slug: "reef-fishing",
    name: "Reef Fishing",
    summary: "Explore wonderful places with our private fishing tour. Reef fishing with a local fisherman who will explain the techniques used and the kind of fish you can find. All tours include free snorkel equipment.",
    duration: "4 hours",
    difficulty: "Easy to Moderate",
    suitability: "All skill levels, ages 8+",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$250 for 2 people",
      "4 hours duration",
      "Through a tour vendor",
    ],
    highlights: [
      "Reef fishing with local fisherman",
      "Free snorkel equipment included",
    ],
    included: [
      "Fishing equipment",
      "Boat and captain",
      "Local fisherman guide",
      "Fishing licenses",
      "Snorkel equipment",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Snapper (red, yellowtail)",
      "Jack crevalle",
      "Various reef fish",
    ],
    whatToBring: [
      "Sunscreen",
      "Hat and sunglasses",
      "Cooler for catch (optional)",
      "Motion sickness medication (if needed)",
      "Camera",
    ],
    seasonal: false,
  },
  {
    slug: "bocas-archipelago-fishing",
    name: "Fishing inside the Bocas Del Toro Archipelago",
    summary: "Explore wonderful places with our private fishing tour. Fishing inside the Bocas Del Toro archipelago with Marcus, our Activities Manager and experienced fisherman. All tours include free snorkel equipment.",
    duration: "4 hours",
    difficulty: "Easy to Moderate",
    suitability: "All skill levels, ages 8+",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$225 for 2 people",
      "4 hours duration",
      "Includes drinks and soft drinks",
    ],
    highlights: [
      "Fishing with Marcus (Activities Manager)",
      "Bocas Del Toro archipelago fishing",
      "Free snorkel equipment included",
      "Drinks and soft drinks included",
    ],
    included: [
      "Fishing equipment",
      "Boat and captain",
      "Bilingual guide (Marcus)",
      "Fishing licenses",
      "Snorkel equipment",
      "Drinks and soft drinks",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Snapper (red, yellowtail)",
      "Jack crevalle",
      "Various archipelago fish",
    ],
    whatToBring: [
      "Sunscreen",
      "Hat and sunglasses",
      "Cooler for catch (optional)",
      "Motion sickness medication (if needed)",
      "Camera",
    ],
    seasonal: false,
  },
  {
    slug: "deep-sea-fishing",
    name: "Deep-sea Fishing",
    summary: "Explore wonderful places with our private deep-sea fishing tour. Deep-sea fishing with Marcus or our local tour vendor. Whole day trip. All tours include free snorkel equipment.",
    duration: "Full day",
    difficulty: "Moderate",
    suitability: "All skill levels, ages 8+",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Prices vary according to length and season",
      "Contact us for current pricing",
    ],
    highlights: [
      "Deep-sea fishing",
      "Fishing with Marcus or local tour vendor",
      "Free snorkel equipment included",
      "Whole day trip",
      "Offshore fishing",
    ],
    included: [
      "Fishing equipment",
      "Boat and captain",
      "Bilingual guide",
      "Fishing licenses",
      "Snorkel equipment",
    ],
    bookingNote: "Prices vary according to length & season. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Wahoo",
      "Kingfish",
      "Tuna",
      "Mahi-mahi (seasonal)",
      "Barracuda",
    ],
    whatToBring: [
      "Sunscreen",
      "Hat and sunglasses",
      "Cooler for catch (optional)",
      "Motion sickness medication (if needed)",
      "Camera",
    ],
    seasonal: false,
  },
  {
    slug: "lobster-catching-snorkeling",
    name: "Lobster Catching & Snorkeling",
    summary: "Explore wonderful places with our unique lobster catching and snorkeling tour. On this unique trip we send you with snorkel gear for you to go diving with a native guide. Learn about how the indigenous people catch fish and lobsters. Tour includes snorkeling at a secret coral bay. If you are lucky you will get to catch your own lobster for dinner. All tours include free snorkel equipment.",
    duration: "Up to 4 hours",
    difficulty: "Moderate",
    suitability: "Swimmers, ages 12+",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Tour:",
      "    $250 for up to 2 people",
      "    Up to 4 hours duration",
      "Lobster Preparation:",
      "    If you catch your own lobster, we prepare it for free",
      "    Sides, appetizers, and dessert not included",
    ],
    highlights: [
      "Lobster catching with native guide",
      "Snorkeling at secret coral bay",
      "Free snorkel equipment included",
      "Catch your own lobster for dinner",
      "Free lobster preparation (if caught)",
    ],
    included: [
      "Snorkel equipment",
      "Boat and captain",
      "Native guide",
      "Lobster preparation (if caught)",
    ],
    bookingNote: "Tour not available during the lobster ban from March 1 - June 30th. If you catch your own lobster we will prepare it for you for free - sides, appetizers and dessert are not included. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Lobster (seasonal)",
      "Tropical fish",
      "Coral reefs",
      "Marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Motion sickness medication (if needed)",
    ],
    seasonal: false,
    seasonNote: "Tour not available during the lobster ban from March 1 - June 30th",
  },
  {
    slug: "massages",
    name: "Massages (Multiple Therapists Available)",
    summary: "Massages are very popular at Dolphin Blue Paradise. Choose from three experienced therapists: Alexia (therapeutic Swedish), Jose (soft tissue), or Jen (certified physical therapist). Massages can be enjoyed over the water at the swim deck, in the salon azul, or where you prefer. Experience deep relaxation surrounded by the sounds of nature, using organic oils and custom aromatherapy blends.",
    duration: "50 minutes",
    difficulty: "Easy",
    suitability: "Relaxation seekers, all ages",
    image: "https://images.unsplash.com/photo-1544161515-4ab6ce6db874?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Alexia (therapeutic Swedish massage): $50 for 50 minutes",
      "    Uses local coconut oil",
      "Jose (soft tissue massage): $50 for 50 minutes",
      "    Uses local coconut oil",
      "Jen (certified physical therapist from New York): $75 for 50 minutes",
      "    Offers deep tissue, trigger point, cupping, and hot stone massages",
      "    $10 extra for cupping, hot stones, or deep tissue",
    ],
    highlights: [
      "Alexia - native resident, therapeutic Swedish massage",
      "Jose - native resident, soft tissue massage",
      "Jen - certified physical therapist from New York",
      "Deep tissue, trigger point, cupping, and hot stone options",
      "On-site service at swim deck, salon azul, or your preferred location",
      "Local coconut oil used by all therapists",
    ],
    included: [
      "50-minute massage session",
      "Local coconut oil (used by Alexia and Jose)",
      "Choice of location (swim deck, salon azul, or your preference)",
      "Professional massage therapist",
    ],
    bookingNote: "Massages are very popular. Must be booked 2 days in advance. Cancellations may incur a full or partial charge. By signing up for a massage the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the therapist, and cannot guarantee availability.",
    wildlife: [],
    whatToBring: [
      "Comfortable clothing",
      "Open mind for relaxation",
      "Swimsuit (if choosing swim deck location)",
    ],
    seasonal: false,
  },
  {
    slug: "hike-with-roque",
    name: "Hike with Roque",
    summary: "Hike with Roque, our native guide and head gardener. How many sloths can you spot? Learn about the lush fauna in our Primary Rainforest. Try and hug a grandfather tree. On this tour you may observe sloths, toucans, frogs, monkeys or even the cayman inside the lagoon.",
    duration: "2-3 hours",
    difficulty: "Moderate",
    suitability: "All ages, must be able to walk on uneven terrain",
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$10 per person",
    ],
    highlights: [
      "Native guide and head gardener",
      "Primary Rainforest exploration",
      "Wildlife spotting (sloths, toucans, frogs, monkeys)",
      "Cayman observation in lagoon",
      "Grandfather tree experience",
    ],
    included: [
      "Native guide (Roque)",
      "Educational tour",
    ],
    bookingNote: "Bring long pants and closed toed shoes for this hike.",
    wildlife: [
      "Sloths",
      "Toucans",
      "Frogs",
      "Monkeys",
      "Cayman (in lagoon)",
      "Various rainforest birds",
    ],
    whatToBring: [
      "Long pants",
      "Closed-toed shoes",
      "Water bottle",
      "Insect repellent",
      "Camera",
      "Hat",
    ],
    seasonal: false,
  },
  {
    slug: "calabash-coconut-bowl",
    name: "Make Your Own Calabash or Coconut Bowl",
    summary: "Make your own calabash or coconut bowl to take home. Roque or Bianca will show you how to make your own calabash or coconut bowls (depending on availability). This is a hands-on activity where you'll learn traditional crafting techniques.",
    duration: "1-2 hours",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1600298881974-6be191ceeda1?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$10 per person",
    ],
    highlights: [
      "Take home your creation",
      "Guided by Roque or Bianca",
    ],
    included: [
      "Materials (calabash or coconut)",
      "Tools and instruction",
      "Take home your bowl",
    ],
    wildlife: [],
    whatToBring: [
      "Comfortable clothing",
      "Camera",
    ],
    seasonal: false,
  },
  {
    slug: "horseback-riding",
    name: "Explore the Jungle of San Cristobal by Horse",
    summary: "Explore the jungle of San Cristobal by horse with a native guide. We will transport you to the other side of the bay where you will meet your horse for the next 90 minutes. You will ride through the jungle of Isla San Cristobal.",
    duration: "90 minutes",
    difficulty: "Easy to Moderate",
    suitability: "Ages 8+, basic riding experience helpful",
    image: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$45 per person",
      "90 minutes duration",
      "Tips for the horses not included",
    ],
    highlights: [
      "Horseback riding through jungle",
      "Native guide",
      "Transportation to starting point",
      "90-minute ride",
    ],
    included: [
      "Horse rental",
      "Native guide",
      "Transportation to starting point",
    ],
    bookingNote: "Must be booked 2 days in advance. Tips for the horses are not included.",
    wildlife: [
      "Jungle birds",
      "Various rainforest wildlife",
    ],
    whatToBring: [
      "Comfortable riding clothes",
      "Closed-toed shoes",
      "Long pants recommended",
      "Camera",
      "Cash for tips",
    ],
    seasonal: false,
  },
  {
    slug: "snorkel-cayo-coral",
    name: "Snorkel at Cayo Coral",
    summary: "Explore wonderful places with our private boat tour to Cayo Coral. All tours include free snorkel equipment. Join Marcus or Josca for a personalized snorkeling experience at one of Bocas del Toro's beautiful coral reefs.",
    duration: "Up to 4 hours",
    difficulty: "Easy",
    suitability: "All ages, swimmers",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$90 for 2 people",
      "Up to 4 hours duration",
      "Includes water and soft drinks on board",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Coral reef exploration",
      "Water and soft drinks included",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
      "Water and soft drinks on board",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Tropical fish",
      "Coral reefs",
      "Marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "snorkel-dolphin-bay-isla-solarte",
    name: "Snorkel around Dolphin Bay and Isla Solarte",
    summary: "Explore wonderful places with our private boat tour around Dolphin Bay and Isla Solarte. All tours include free snorkel equipment. Join Marcus or Josca for a personalized snorkeling experience in the beautiful waters around these islands.",
    duration: "Up to 4 hours",
    difficulty: "Easy",
    suitability: "All ages, swimmers",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$80 for 2 people",
      "Up to 4 hours duration",
      "Includes water and soft drinks on board",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Dolphin Bay and Isla Solarte exploration",
      "Water and soft drinks included",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
      "Water and soft drinks on board",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Tropical fish",
      "Marine life",
      "Dolphins (possible sightings)",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "zapatilla-survivor-island",
    name: "Zapatilla - AKA Survivor Island",
    summary: "Explore wonderful places with our private boat tour to Zapatilla, also known as Survivor Island. All tours include free snorkel equipment. Join Marcus or Josca for a full day adventure to this pristine island paradise.",
    duration: "Full day (weather dependent)",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$125 for 2 people",
      "Duration: as long as weather allows (leaves early morning)",
      "Includes soft drinks and water on board",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Survivor Island (Zapatilla) visit",
      "Soft drinks and water on board",
      "Early morning departure",
      "Optional packed lunch and picnic at the beach",
      "Optional stop at Cayo Coral on the way home for lunch and snorkeling",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
      "Soft drinks and water on board",
    ],
    bookingNote: "We leave early in the morning and go as long as the weather allows. Order a packed lunch and picnic at the beach or stop at Cayo Coral on the way home for lunch and a little bit of snorkeling. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Tropical fish",
      "Marine life",
      "Coastal birds",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
      "Cash for lunch (optional)",
    ],
    seasonal: false,
  },
  {
    slug: "playa-estrella-starfish-beach",
    name: "Playa Estrella - Starfish Beach",
    summary: "Explore wonderful places with our private boat tour to Playa Estrella, also known as Starfish Beach. All tours include free snorkel equipment. Join Marcus or Josca for a visit to this beautiful beach famous for its starfish.",
    duration: "Half-day",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$130 for 2 people",
      "Includes soft drinks and water on board",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Starfish Beach visit",
      "Soft drinks and water on board",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
      "Soft drinks and water on board",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Starfish",
      "Tropical fish",
      "Marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "playa-estrella-bird-island",
    name: "Playa Estrella & Bird Island",
    summary: "Explore wonderful places with our private boat tour to Playa Estrella (Starfish Beach) and Bird Island. All tours include free snorkel equipment. Join Marcus or Josca for a combined tour visiting both beautiful locations.",
    duration: "Half-day",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$165 for 2 people",
      "Includes soft drinks and water on board",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Starfish Beach visit",
      "Bird Island visit",
      "Soft drinks and water on board",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
      "Soft drinks and water on board",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Starfish",
      "Birds",
      "Tropical fish",
      "Marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "red-frog-beach",
    name: "Red Frog Beach",
    summary: "Explore wonderful places with our private boat tour to Red Frog Beach. Spend the day at Red Frog Beach where you can enjoy the beach, ziplining, or just take a walk in the resort. All tours include free snorkel equipment.",
    duration: "Full day",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$100 for 2 people",
      "Does not include entrance to Red Frog Beach",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Red Frog Beach access",
      "Ziplining available (requires prior reservation)",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
    ],
    bookingNote: "Does not include entrance to Red Frog Beach. On Red Frog beach you can enjoy the beach, ziplining, or just take a walk in the resort. Ziplining requires prior reservation. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by outside tour vendors.",
    wildlife: [
      "Red frogs",
      "Coastal birds",
      "Marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Camera",
      "Water bottle",
      "Cash for entrance fee and activities",
    ],
    seasonal: false,
  },
  {
    slug: "dolphin-bay-sunset-cruise",
    name: "Dolphin Bay Sunset Cruise",
    summary: "Explore wonderful places with our private boat tour. Enjoy a peaceful 30-minute sunset cruise around Dolphin Bay. Perfect for couples or small groups looking to end the day with beautiful views and tranquility. All tours include free snorkel equipment.",
    duration: "30 minutes",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$35 for 2 people",
      "30 minutes duration",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Sunset views",
      "Dolphin Bay scenery",
    ],
    included: [
      "Boat transportation",
      "Bilingual guide (Marcus or Josca)",
      "Snorkel equipment",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Dolphins (possible sightings)",
      "Coastal birds",
    ],
    whatToBring: [
      "Camera",
      "Light jacket",
    ],
    seasonal: false,
  },
  {
    slug: "tubing-dolphin-bay",
    name: "Tubing around Dolphin Bay",
    summary: "Explore wonderful places with our tubing adventure around Dolphin Bay. Enjoy a fun and exciting tubing experience in the beautiful waters. All tours include free snorkel equipment.",
    duration: "Up to 30 minutes per person",
    difficulty: "Moderate",
    suitability: "Ages 12+, swimmers",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Up to $35 per person",
      "Up to 30 minutes duration",
    ],
    highlights: [
      "Tubing adventure",
      "Free snorkel equipment included",
      "Dolphin Bay exploration",
    ],
    included: [
      "Tubing equipment",
      "Boat and driver",
      "Snorkel equipment",
      "Safety equipment",
    ],
    bookingNote: "Outside vendor tours must be booked at least 24 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Marine life",
      "Dolphins (possible sightings)",
    ],
    whatToBring: [
      "Swimsuit",
      "Sunscreen",
      "Towel",
      "Change of clothes",
    ],
    seasonal: false,
  },
  {
    slug: "diving",
    name: "Diving",
    summary: "Explore the underwater world of Bocas del Toro with La Buga Dive & Surf. Diving courses available from beginners to experienced divers. Discover vibrant coral reefs and diverse marine life. Note: $90 boat transfer for 2 people not included in price.",
    duration: "Half-day to full-day",
    difficulty: "Moderate to Advanced",
    suitability: "Swimmers, ages 12+",
    image: "https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Diving Courses:",
      "    Prices start at $265",
      "    Courses available for all levels (beginners to experienced)",
      "Boat Transfer:",
      "    $90 for 2 people (not included in diving price)",
    ],
    highlights: [
      "Professional diving instruction",
      "Courses for all levels (beginners to experienced)",
      "Coral reef exploration",
      "Certified instructors",
      "La Buga Dive & Surf",
    ],
    included: [
      "Diving equipment",
      "Professional instruction",
      "Boat transportation (from dive center)",
    ],
    bookingNote: "$90 boat transfer for 2 people not included in price. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Tropical reef fish",
      "Coral formations",
      "Sea turtles",
      "Rays",
      "Various marine life",
    ],
    whatToBring: [
      "Swimsuit",
      "Reef-safe sunscreen",
      "Towel",
      "Camera (waterproof)",
      "Certification card (if certified)",
    ],
    seasonal: false,
  },
  {
    slug: "atv-bike-rentals",
    name: "ATV and Bike Rentals",
    summary: "Explore Bocas del Toro on wheels with ATV and bike rentals from Flying Pirates. Discover the island at your own pace with 4-hour or full-day rental options. Note: $90 boat transfer for 2 people not included in price.",
    duration: "4 hours to full-day",
    difficulty: "Easy to Moderate",
    suitability: "Ages 16+ for ATV, ages 12+ for bikes",
    image: "https://images.unsplash.com/photo-1558980664-1db506751c6c?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "ATV Rentals (Flying Pirates):",
      "    4 hours: $110 for one person",
      "    Full day: $150 for one person",
      "    Additional passenger: $10",
      "Bike rentals available (contact for pricing)",
      "Boat transfer: $90 for 2 people (not included in rental price)",
    ],
    highlights: [
      "ATV rentals",
      "Bike rentals",
      "Flying Pirates",
      "Flexible rental periods (4 hours or full day)",
      "Passenger option available",
    ],
    included: [
      "ATV or bike rental",
      "Safety equipment",
    ],
    bookingNote: "$90 boat transfer for 2 people not included in price. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Coastal birds",
      "Island wildlife",
    ],
    whatToBring: [
      "Comfortable clothing",
      "Closed-toed shoes",
      "Sunscreen",
      "Camera",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "plastic-bottle-village",
    name: "Plastic Bottle Village",
    summary: "Visit the Frenchman Robert Bezeau who collected over 1 million water bottles and turned them into his own home and an entire village. Learn about sustainable building practices and environmental conservation in this unique attraction. Note: $90 boat transfer for 2 people not included in price.",
    duration: "2-3 hours",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1497435334941-8c899ee9e8e9?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "Entrance fee required (paid at village)",
      "Boat transfer: $90 for 2 people (not included)",
    ],
    highlights: [
      "Innovative sustainable architecture",
      "Over 1 million plastic bottles used",
      "Created by Frenchman Robert Bezeau",
      "Entire village made from plastic bottles",
    ],
    included: [
      "Boat transportation to Bocas Town",
    ],
    bookingNote: "$90 boat transfer for 2 people not included in price. Entrance fee paid directly at the village. Visit http://www.plasticbottlevillage-theline.com/ for more information. Outside vendor tours must be booked at least 24-48 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [],
    whatToBring: [
      "Comfortable walking shoes",
      "Camera",
      "Cash for entrance fee",
      "Water bottle",
    ],
    seasonal: false,
  },
  {
    slug: "medicinal-plants-tour",
    name: "Medicinal Plants Tour",
    summary: "Explore wonderful places with our private boat tour. On this Friday-only tour, visit with the women of the San Cristobal village. You will learn about medicinal and tribal purposes of the local plants, learn how they prepare the fibers and dyes naturally for clothing and weaving bags. Finish with a tribal lunch prepared in the village. All tours include free snorkel equipment.",
    duration: "Full day",
    difficulty: "Easy",
    suitability: "All ages",
    image: "https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?w=1200&h=800&fit=crop&q=80",
    pricing: [
      "$220 per couple",
      "Additional guests: $85 each",
      "Includes transfer to San Cristobal village, drinks on board, tour & lunch",
    ],
    highlights: [
      "Private boat tour with Marcus or Josca",
      "Free snorkel equipment included",
      "Traditional plant uses",
      "Fiber and dye preparation",
      "Weaving techniques",
      "Tribal lunch",
      "Visit with women of San Cristobal village",
    ],
    included: [
      "Transfer to San Cristobal village",
      "Drinks on board",
      "Guided tour",
      "Tribal lunch",
      "Snorkel equipment",
    ],
    bookingNote: "Tour must be booked 72 hours prior and is dependent on availability. Departure from DBP at 8:15 am. Friday only tour. Outside vendor tours must be booked at least 24 hours prior. Cancellations may incur a full or partial charge. By signing up for a tour the guests agree that Dolphin Blue Paradise is not liable for any accidents, guest belongings or weather related cancellations. Dolphin Blue Paradise is not liable for any last minute changes by the tour vendor.",
    wildlife: [
      "Medicinal plants",
      "Local flora",
    ],
    whatToBring: [
      "Comfortable walking shoes",
      "Camera",
      "Respectful clothing",
      "Water bottle",
    ],
    seasonal: false,
  },
];

export const impactHighlights = [
  {
    title: "Off-Grid Energy",
    description: "100% solar-powered operations with energy monitoring to minimize footprint.",
  },
  {
    title: "Rainwater Stewardship",
    description: "Closed-loop rainwater collection and purification for drinking and daily use.",
  },
  {
    title: "Garden-to-Table",
    description: "Tropical fruit, herbs, and vegetables harvested onsite for every menu.",
  },
  {
    title: "Zero-Waste Mindset",
    description: "Composting kitchen scraps and replacing plastics with reusable amenities.",
  },
];

export const donationWishList = [
  "Basic clothing & shoes",
  "School supplies and backpacks",
  "Solar chargers & lanterns",
  "Rainwater catchment systems",
  "Mosquito nets & life vests",
  "Laptop donations",
  "Sports equipment",
  "Headlamps or bike lights",
];

export const travelRoutes = [
  {
    title: "From Panama City",
    options: [
      "Domestic flight via Marcos A. Gelabert (PAC) to Bocas del Toro (BOC) with Air Panama or Fly Trip.",
      "Private charter flights starting at $1680 each way for up to 3 guests.",
      "Private 4x4 car service (7–10 hours) connecting to our captain in Tierra Oscura.",
      "Tranceibosa overnight coach to Almirante with boat transfer to the resort.",
    ],
  },
  {
    title: "From Costa Rica",
    options: [
      "Sansa Air flights from San José (SJO) to Bocas del Toro on Tue/Thu/Sun.",
      "Caribe Shuttle service from San José or Puerto Viejo direct to Almirante harbor.",
    ],
  },
  {
    title: "From David or Boquete",
    options: [
      "Private driver in 4x4 with transfer from Tierra Oscura dock.",
      "Public buses via Rambala and community taxi to Tierra Oscura.",
      "Self-drive with secure local parking and scheduled boat pickup.",
    ],
  },
];

/**
 * FAQ Data
 * 
 * ⚠️ IMPORTANT NOTE FOR YUH:
 * The FAQ answers below are placeholders. Please replace each answer with actual information
 * about your property. Each FAQ has a note indicating what specific information needs to be confirmed.
 */
export const faqs = [
  // Booking FAQs
  {
    question: "How do I book and what are the payment terms?",
    answerItems: [
      "Booking methods (widget, WhatsApp, email, phone)",
      "Deposit percentage required",
      "When balance is due",
      "Accepted payment methods (credit cards, bank transfer, cash, etc.)",
      "Recommended booking timeline for peak season",
      "Whether last-minute bookings are accepted",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  {
    question: "What is the minimum stay and do you offer group rates?",
    answerItems: [
      "Minimum stay requirement (nights)",
      "Number of nights required for complimentary transfers",
      "Extended stay discount thresholds",
      "Group size that qualifies for special rates",
      "What group benefits are included (concierge coordination, etc.)",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // Accessibility FAQs
  {
    question: "Is the property accessible for guests with mobility limitations?",
    answerItems: [
      "Actual number of steps per cabana/room type",
      "Pathway conditions (natural, paved, etc.)",
      "Whether wheelchair accessibility is available anywhere on property",
      "What accommodations can be made for guests with mobility considerations",
      "Whether you can accommodate specific needs with advance notice",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // Policy FAQs
  {
    question: "What are your policies on pets, children, and safety?",
    answerItems: [
      "Pet policy (allowed/not allowed, service animals policy)",
      "Children policy (age restrictions, free stay age if applicable)",
      "Safety protocols in place (24/7 staff, first aid, emergency systems)",
      "Safety briefings provided (water activities, etc.)",
      "Any age restrictions for activities",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  {
    question: "What is your cancellation and refund policy?",
    answerItems: [
      "Cancellation timeline tiers (e.g., 30+ days, 14-30 days, within 14 days)",
      "Refund percentages for each tier",
      "Processing fees if any",
      "Credit toward future stays policy",
      "Weather-related disruption policy",
      "Refund processing time",
      "Travel insurance recommendation",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // Amenities FAQs
  {
    question: "What about Wi-Fi, electricity, and water?",
    answerItems: [
      "Wi-Fi type (satellite, etc.) and actual speeds/capabilities (can it handle video calls?)",
      "Electricity system (solar percentage, battery backup, generator backup)",
      "Outlet voltage (110V, 220V, both?)",
      "Water system details (rainwater collection, purification process, safety standards)",
      "Cellular coverage availability",
      "Wi-Fi calling recommendation",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // Inclusions FAQs
  {
    question: "What is included in my stay and what are extra fees?",
    answerItems: [
      "Breakfast for 2 is included in the room rate (served 8:00 am to 9:30 am)",
      "Free Wi-Fi available property-wide",
      "Purified rainwater provided in all rooms",
      "Complimentary arrival and departure transfers from Bocas Town or airport for guests staying 4+ nights",
      "Free activities: Snorkeling from swim platform, kayaking, stand-up paddleboarding",
      "Concierge service for planning your stay",
      "What costs extra: Lunch, dinner, alcoholic beverages, excursions, transfers for stays less than 4 nights, spa services",
      "Lunch is a la carte menu (12:00 pm to 2:30 pm). Lunch packs available if ordered in advance",
      "Dinner is a 3-course prix fixe menu (7:00 pm to 9:30 pm)",
      "Blå Bar offers all-day snacks and cocktails",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // Dining FAQs
  {
    question: "What are the meal times and what is included?",
    answerItems: [
      "Breakfast: 8:00 am to 9:30 am - Breakfast for 2 included in the room rate. Always served with fresh tropical fruits, fresh made juice, home baked bread, homemade jams, homemade yogurt with homemade coconut granola, and a different main dish (egg) each day. Filter coffee and tea included.",
      "Lunch: 12:00 pm to 2:30 pm - French-based menu with quiche, flatbreads, homemade pasta, croque madame, croque monsieur, and salads. A la carte menu. We also provide guests with lunch packs if they order in advance.",
      "Dinner: 7:00 pm to 9:30 pm - 3-course prix fixe menu in an intimate, tranquil setting. Food is sourced locally when possible. We grow as much of our fruit and vegetables as possible and we catch our fish ourselves. Our staff catches lobster, crabs, conch, and octopus when possible.",
      "Blå Bar: Open anytime for hotel guests. For outside guests, we are open upon reservation. Hours are flexible. Offers all-day snacks and delightful cocktails.",
      "We always vary what we serve based on our own harvest. Menus are created weekly with our gardener, basing the menu on the week's harvest.",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
  // General FAQs
  {
    question: "Can you accommodate dietary restrictions?",
    answerItems: [
      "Yes, most dishes can be made vegetarian.",
      "We have a number of dishes that are vegan.",
      "We can cater to gluten-free dietary choices. Being remote, we cannot guarantee 100% gluten-free environment. When a guest notifies us of gluten sensitivities, our chef contacts the guest to find out severity and options.",
      "We do bake our own gluten-free breads for guests and are able to accommodate most sensitivities.",
      "Guests with Celiac disease should consult with their doctor to determine if our precautions are enough.",
      "48-hour advance notice required for dietary accommodations.",
    ],
    notes: "", // Yuh: Add your comments or thoughts here
  },
];

export const galleryFilters = [
  "Rooms",
  "Dining",
  "Experiences",
  "Nature",
  "Community",
];
